/**
 * Scans source files and generates a lucide-react vendor shim
 * that re-exports ONLY the icons actually used in the codebase.
 *
 * Usage: bun lucide-shim-gen.ts [srcDir...]
 * Output: src/tools/lucide-vendor-shim.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, extname, resolve } from "path";

const defaultScanDirs = [
  resolve(import.meta.dir, "../../../.."),
  resolve(import.meta.dir, "../../../../../club-portal/front"),
  resolve(import.meta.dir, "../../../../../../../saas/public/front/front-landings"),
];

const scanDirs = process.argv.slice(2).length > 0
  ? process.argv.slice(2).map((d) => resolve(d))
  : defaultScanDirs;

const IMPORT_RE = /from\s+["']lucide-react["'][^;]*\nimport\s*\{([^}]+)\}\s*from\s+["']lucide-react["']/gs;
const NAMED_IMPORT_RE = /import\s*\{([^}]+)\}\s*from\s+["']lucide-react["']/g;

function findFiles(dir: string): string[] {
  let files: string[] = [];
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name === "dist" || entry.name === ".git") continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        files = files.concat(findFiles(full));
      } else if ([".ts", ".tsx"].includes(extname(entry.name))) {
        files.push(full);
      }
    }
  } catch {}
  return files;
}

const icons = new Set<string>();

for (const dir of scanDirs) {
  for (const file of findFiles(dir)) {
    const content = readFileSync(file, "utf-8");
    let match: RegExpExecArray | null;
    NAMED_IMPORT_RE.lastIndex = 0;
    while ((match = NAMED_IMPORT_RE.exec(content)) !== null) {
      for (const name of match[1].split(",")) {
        const trimmed = name.trim().split(/\s+as\s+/)[0].trim();
        if (trimmed && /^[A-Z]/.test(trimmed)) {
          icons.add(trimmed);
        }
      }
    }
  }
}

const sorted = [...icons].sort();
const shimPath = resolve(import.meta.dir, "lucide-vendor-shim.ts");
const lines = [
  `// Auto-generated by lucide-shim-gen.ts — DO NOT EDIT`,
  `// Contains only icons actually used in the codebase (${sorted.length} icons)`,
  `export { ${sorted.join(", ")} } from "lucide-react";`,
];

writeFileSync(shimPath, lines.join("\n") + "\n");
console.log(`Generated ${shimPath} with ${sorted.length} icons: ${sorted.join(", ")}`);
