#!/usr/bin/env bun
/**
 * Builder-stage bundler for the `ms` and `ui` images.
 *
 * It bundles one thing: the server. Not the modules — those are not in the
 * image at all. A microservice or a microfrontend is built once by
 * `core/tools/registry`, published by digest, and fetched from ptah at boot,
 * so the set of modules is no longer a property of the image and rolling one
 * forward no longer means rebuilding one.
 *
 * That is a second step away from generated Containerfiles. The generator was
 * removed when the module list moved from build time to the Solution; this
 * removes the modules themselves, and what is left in the image is the part
 * that genuinely differs between `ms` and `ui`.
 *
 * What ships is a bundle, not a source tree: the runtime stage copies `out/`
 * onto Cruller and nothing else. No workspace `node_modules`, no zig sources,
 * no modules of any kind.
 *
 * Output layout under `--out`:
 *
 *   app/server.js       bundled production entrypoint
 *   app/package.json    external prod deps only (installed separately)
 *   plugins/bin-libs/…  the dlopen'd .so files for this arch
 */

import { existsSync, mkdirSync } from "node:fs";
import { basename, join, resolve } from "node:path";

type Role = "ms" | "ui";

type Options = {
	role: Role;
	/** Directory holding `converged/` and, when layered, the product. */
	root: string;
	/** Converged checkout — the base layer. */
	projectDir: string;
	/** Product checkout when one extends converged, else undefined. */
	childProjectDir?: string;
	outDir: string;
	/** Absolute path the runtime will see the client delivery at, `ui` only. */
	deliveryMountPath: string;
	/** Absolute path the runtime will see the landing's assets at, `ui` only. */
	publicMountPath: string;
};

function parseArgs(argv: string[]): Options {
	const values = new Map<string, string>();
	for (const arg of argv) {
		const match = /^--([^=]+)=(.*)$/.exec(arg);
		if (match) values.set(match[1], match[2]);
	}

	const role = values.get("role");
	if (role !== "ms" && role !== "ui") {
		throw new Error("--role=<ms|ui> is required");
	}
	const root = values.get("root");
	if (!root) throw new Error("--root=<dir holding converged/> is required");
	const projectDir = values.get("project-dir");
	if (!projectDir)
		throw new Error("--project-dir=<converged checkout> is required");
	const outDir = values.get("out");
	if (!outDir) throw new Error("--out=<dir> is required");

	const childProjectDir = values.get("child-project-dir")?.trim();
	return {
		role,
		root: resolve(root),
		projectDir: resolve(projectDir),
		childProjectDir:
			childProjectDir && childProjectDir !== projectDir
				? resolve(childProjectDir)
				: undefined,
		outDir: resolve(outDir),
		deliveryMountPath: values.get("delivery-mount") ?? "/app/dist/front",
		publicMountPath: values.get("public-mount") ?? "/app/public",
	};
}

/**
 * The landing host belongs to the product, not to converged: it statically
 * imports its own blocks, SPA plugin and locale set. The dev runner picks it
 * the same way (`core/tools/dev/src/cli.ts`), and a built image that used the
 * base host instead would serve converged blocks against a delivery compiled
 * from the product's — the exact mismatch `spa/src/build/layout.ts` guards.
 */
function resolveLandingDir(options: Options): string {
	const candidates = [options.childProjectDir, options.projectDir]
		.filter((value): value is string => Boolean(value))
		.map((projectDir) => join(projectDir, "core/frontend/landing"));
	for (const dir of candidates) {
		if (
			existsSync(join(dir, "src/plugin.tsx")) ||
			existsSync(join(dir, "src/plugin.ts"))
		) {
			return dir;
		}
	}
	throw new Error(
		`[bundle] no landing host found in: ${candidates.join(", ")}`,
	);
}

/**
 * A generated entry rather than the project's own `src/dev.ts`, because the
 * two disagree on exactly one thing: a source run finds `public/` and `dist/`
 * next to itself, and a single bundled file cannot. Everything else — which
 * plugins, which host — is taken from the project unchanged.
 */
async function writeUiEntry(
	options: Options,
	landingDir: string,
): Promise<string> {
	const projectRoot = options.childProjectDir ?? options.projectDir;
	const spaPlugin = join(projectRoot, "core/frontend/spa/src/plugin.ts");
	const spaImport = existsSync(spaPlugin)
		? spaPlugin
		: join(options.projectDir, "core/frontend/spa/src/plugin.ts");
	const landingPlugin = existsSync(join(landingDir, "src/plugin.tsx"))
		? join(landingDir, "src/plugin.tsx")
		: join(landingDir, "src/plugin.ts");
	const devServer = join(
		options.projectDir,
		"core/frontend/landing/src/dev-server.ts",
	);

	// `production` is a literal, not `process.env.NODE_ENV`: the bundler folds
	// that read at build time, and this step does not run with NODE_ENV set — the
	// image would then boot into the dev branch and try to rebuild the delivery
	// from sources it does not carry.
	const source = `// Generated by core/containers/bundle.ts — do not edit.
import spaPlugin from ${JSON.stringify(spaImport)};
import landingPlugin from ${JSON.stringify(landingPlugin)};
import { startLandingDevServer, requiredLandingEnv } from ${JSON.stringify(devServer)};

const production = true;

await startLandingDevServer({
	name: ${JSON.stringify(`${basename(projectRoot)}-landing`)},
	projectDir: requiredLandingEnv("PROJECT_DIR"),
	publicDir: ${JSON.stringify(options.publicMountPath)},
	spa: spaPlugin({ production, distDir: ${JSON.stringify(options.deliveryMountPath)} }),
	landing: landingPlugin({ production, publicDir: ${JSON.stringify(options.publicMountPath)} }),
});
`;
	const path = join(options.outDir, "entry.ts");
	await Bun.write(path, source);
	return path;
}

/**
 * The same entry the dev runner starts. It is one maintained code path: what
 * differs in the image is MODULE_PROXY, which switches module resolution from
 * scanning source to fetching from the registry.
 */
function resolveServerEntry(options: Options): string {
	const entry = join(options.projectDir, "core/backend/src/dev.ts");
	if (!existsSync(entry)) {
		throw new Error(`[bundle] server entrypoint not found: ${entry}`);
	}
	return entry;
}

/** One place for the build flags every bundle in this image shares. */
async function run(
	config: Parameters<typeof Bun.build>[0],
	label: string,
): Promise<void> {
	const result = await Bun.build({
		target: "bun",
		format: "esm",
		minify: true,
		// Both load prebuilt native binaries of their own. Bundled, the copy
		// that ships cannot find them, and only at the first call.
		external: ["sharp", "lightningcss"],
		...config,
	});
	if (!result.success) {
		for (const log of result.logs) console.error(log);
		throw new Error(`[bundle] ${label} build failed`);
	}
	console.log(`[bundle] ${label}: ${result.outputs.length} chunks`);
}

async function build(options: Options): Promise<void> {
	mkdirSync(join(options.outDir, "app"), { recursive: true });
	const entry =
		options.role === "ms"
			? resolveServerEntry(options)
			: await writeUiEntry(options, resolveLandingDir(options));
	if (options.role === "ui") {
		console.log(`[bundle] landing host: ${resolveLandingDir(options)}`);
	}
	await run(
		{
			entrypoints: [entry],
			outdir: join(options.outDir, "app"),
			naming: "server.js",
		},
		"server",
	);
}

await build(parseArgs(Bun.argv.slice(2)));
