import { getTableColumns } from "front-core/table";

const fields = [
	{ id: "ts", title: "Time", type: "date", tableVisible: true, width: 170 },
	{
		id: "event_type",
		title: "Event",
		type: "text",
		tableVisible: true,
		width: 130,
	},
	{
		id: "audience_type",
		title: "Audience",
		type: "text",
		tableVisible: true,
		width: 130,
	},
	{
		id: "content_type",
		title: "Content type",
		type: "text",
		tableVisible: true,
		width: 150,
	},
	{
		id: "content_id",
		title: "Content block",
		type: "text",
		tableVisible: true,
		minWidth: 170,
	},
	{ id: "url", title: "Page", type: "text", tableVisible: true, minWidth: 240 },
	{
		id: "visitor_id",
		title: "Visitor",
		type: "text",
		tableVisible: true,
		minWidth: 170,
	},
	{
		id: "session_id",
		title: "Session",
		type: "text",
		tableVisible: true,
		minWidth: 170,
	},
	{
		id: "trusted_clicks",
		title: "Clicks",
		type: "number",
		tableVisible: true,
		width: 90,
	},
	{
		id: "visible_ms",
		title: "Visible ms",
		type: "number",
		tableVisible: true,
		width: 110,
	},
];

export const analyticsColumns = getTableColumns(fields);

export const analyticsIpSessionColumns = getTableColumns([
	{
		id: "id",
		title: "Session ID",
		type: "text",
		tableVisible: true,
		width: 205,
	},
	{
		id: "ip_address",
		title: "IP address",
		type: "text",
		tableVisible: true,
		width: 145,
	},
	{
		id: "network",
		title: "Network",
		type: "text",
		tableVisible: true,
		minWidth: 170,
	},
	{
		id: "country_name",
		title: "Country",
		type: "text",
		tableVisible: true,
		width: 140,
	},
	{
		id: "city_name",
		title: "City",
		type: "text",
		tableVisible: true,
		minWidth: 150,
	},
	{
		id: "user_type",
		title: "Visitor type",
		type: "text",
		tableVisible: true,
		width: 120,
	},
	{
		id: "device_type",
		title: "Device",
		type: "text",
		tableVisible: true,
		width: 105,
	},
	{
		id: "utm_source",
		title: "Traffic source",
		type: "text",
		tableVisible: true,
		minWidth: 140,
	},
	{
		id: "screen",
		title: "Screen",
		type: "text",
		tableVisible: true,
		width: 105,
	},
	{
		id: "url",
		title: "Last page",
		type: "text",
		tableVisible: true,
		minWidth: 230,
	},
	{
		id: "event_count",
		title: "Events",
		type: "number",
		tableVisible: true,
		width: 90,
	},
	{
		id: "duration_seconds",
		title: "Duration (s)",
		type: "number",
		tableVisible: true,
		width: 110,
	},
	{
		id: "clicks",
		title: "Clicks",
		type: "number",
		tableVisible: true,
		width: 85,
	},
	{
		id: "visible_ms",
		title: "Visible ms",
		type: "number",
		tableVisible: true,
		width: 105,
	},
	{
		id: "last_seen",
		title: "Last seen",
		type: "date",
		tableVisible: true,
		width: 170,
	},
	{
		id: "first_seen",
		title: "Started",
		type: "date",
		tableVisible: true,
		width: 170,
	},
]);
