export type {
	Contact,
	Lead,
	LeadEvent,
	LeadListParams,
	LeadTag,
	Offer,
	Outreach,
	OutreachCandidate,
	OutreachTarget,
	OutreachTargetInput,
	OutreachTargetListParams,
	OutreachTargetStatusUpdate,
	PaginatedResult,
	PaginationParams,
	SalesService,
	Statistic,
	Touch,
} from "g-sales";
