export type {
  EquipmentId,
  EquipmentLogId,
  ScheduleSlotId,
  JobId,
  ISODateString,
  EquipmentStatus,
  EquipmentLogSeverity,
  EquipmentLogType,
  ScheduleSlotStatus,
  Equipment,
  EquipmentInput,
  EquipmentPatch,
  EquipmentStateInput,
  EquipmentListParams,
  EquipmentLog,
  EquipmentLogInput,
  EquipmentLogListParams,
  ScheduleSlot,
  ScheduleSlotInput,
  ScheduleSlotPatch,
  ScheduleListParams,
  EquipmentStatusCount,
  EquipmentDashboard,
  EquipmentService,
  PaginatedResult,
} from "g-equipment";
