import { resolve } from "path";
import { mkdir, rm, writeFile } from "fs/promises";
import type { BuildConfig, GeneratorContext } from "../types";
import { normalizePresetName, resolvePreset } from "../resolver";
import { generateContainerfiles } from "../generators/containerfile";
import { generateKubernetesManifests } from "../generators/kubernetes";
import { generateRuntimeConfigs } from "../generators/server";


const PROJECTS_DIR = resolve(import.meta.dir, "../../../../../");
const CONTAINER_IGNORE_FILENAME = ".containerignore";

function buildContainerIgnoreContent(
  projectName: string,
  parentProjectName?: string,
): string {
  const allowedProjects = [
    projectName,
    ...(parentProjectName ? [parentProjectName] : []),
  ];

  const lines = [
    "# Auto-generated by configurator. Passed to podman via --ignorefile.",
    "# Ignore everything by default; allow only required build sources.",
    "**",
    "!clarity/",
    "!clarity/projects/",
    ...allowedProjects.flatMap((name) => [
      `!clarity/projects/${name}/`,
      `!clarity/projects/${name}/**`,
    ]),
    "!saas/",
    "!saas/public/",
    "!saas/public/front/",
    "!saas/public/front/front-landings/",
    "!saas/public/front/front-landings/**",
    "",
    "# Exclude heavy local/build artifacts inside allowed projects.",
    ...allowedProjects.flatMap((name) => [
      `clarity/projects/${name}/node_modules`,
      `clarity/projects/${name}/node_modules/**`,
      `clarity/projects/${name}/**/node_modules`,
      `clarity/projects/${name}/**/node_modules/**`,
      `clarity/projects/${name}/.bun-install`,
      `clarity/projects/${name}/.bun-install/**`,
      `clarity/projects/${name}/.zig-cache`,
      `clarity/projects/${name}/.zig-cache/**`,
      `clarity/projects/${name}/**/.zig-cache`,
      `clarity/projects/${name}/**/.zig-cache/**`,
      `clarity/projects/${name}/**/coverage`,
      `clarity/projects/${name}/**/coverage/**`,
      `clarity/projects/${name}/**/*.log`,
    ]),
  ];

  return `${lines.join("\n")}\n`;
}

export interface BuildOptions {
  projectName: string;
  preset: string;
  outputDir: string;
  namespace?: string;
}

async function loadConfig(projectDir: string): Promise<BuildConfig> {
  const configPath = resolve(projectDir, "config.json");
  const file = Bun.file(configPath);
  if (!(await file.exists())) {
    throw new Error(`Config not found: ${configPath}`);
  }
  return await file.json() as BuildConfig;
}

function mergeStringArrays(base: string[] = [], extra: string[] = []): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of [...base, ...extra]) {
    if (seen.has(item)) continue;
    seen.add(item);
    out.push(item);
  }
  return out;
}

export async function runBuild({
  projectName,
  preset,
  outputDir,
  namespace,
}: BuildOptions) {
  const projectDir = resolve(PROJECTS_DIR, projectName);
  const config = await loadConfig(projectDir);
  const targetNamespace = namespace || config.name;

  let parentDir: string | undefined;
  let mergedConfig = config;

  if (config.extends) {
    parentDir = resolve(PROJECTS_DIR, config.extends);
    const parentConfig = await loadConfig(parentDir);

    mergedConfig = {
      ...config,
      baseImage: config.baseImage || parentConfig.baseImage,
      spa: {
        core: config.spa.core || parentConfig.spa.core,
        microfrontends: mergeStringArrays(
          parentConfig.spa.microfrontends,
          config.spa.microfrontends,
        ),
      },
      back: {
        core: config.back.core || parentConfig.back.core,
        microservices: {
          ...parentConfig.back.microservices,
          ...config.back.microservices,
        },
      },
      runtimeDeps: config.runtimeDeps ?? parentConfig.runtimeDeps,
      frontend: config.frontend ?? parentConfig.frontend,
      storage: {
        ...parentConfig.storage,
        ...config.storage,
        overrides: {
          ...parentConfig.storage?.overrides,
          ...config.storage?.overrides,
        },
      },
    };


  }

  const presetName = normalizePresetName(mergedConfig, preset);

  console.log(`Project: ${projectName}`);
  console.log(`Preset:  ${presetName}`);

  const containers = resolvePreset(
    mergedConfig,
    presetName,
    projectName,
    parentDir ? config.extends! : undefined,
  );

  console.log(`Resolved ${containers.length} container(s):`);
  for (const c of containers) {
    console.log(
      `  - ${c.name}: ${c.microservices.length} services, ${c.microfrontends.length} MFs, spa=${c.spa}, landing=${c.landing}`,
    );
  }

  // Output goes into deployment/{preset}/
  const presetDir = resolve(outputDir, presetName);

  const ctx: GeneratorContext = {
    config: mergedConfig,
    preset: presetName,
    namespace: targetNamespace,
    containers,
    outputDir: resolve(presetDir),
    projectDir,
    parentProjectDir: parentDir,
    storage: mergedConfig.storage,
  };

  // Create output directories
  const containersDir = resolve(presetDir, "containers");
  const helmDir = resolve(presetDir, "helm");
  await rm(containersDir, { recursive: true, force: true });
  await rm(helmDir, { recursive: true, force: true });
  await mkdir(containersDir, { recursive: true });
  await mkdir(helmDir, { recursive: true });

  // Generate Containerfiles
  console.log("\nGenerating Containerfiles...");
  const containerfiles = await generateContainerfiles(ctx);
  for (const [filename, content] of containerfiles) {
    const path = resolve(containersDir, filename);
    await writeFile(path, content);
    console.log(`  ${path}`);
  }

  const parentProjectName = config.extends?.split("/").pop();
  const ignoreFilePath = resolve(containersDir, CONTAINER_IGNORE_FILENAME);
  await writeFile(
    ignoreFilePath,
    buildContainerIgnoreContent(projectName, parentProjectName),
  );
  console.log(`  ${ignoreFilePath}`);

  // Generate Helm chart templates via cdk8s
  console.log("\nGenerating Helm chart...");
  await rm(resolve(helmDir, "templates"), { recursive: true, force: true });
  await mkdir(resolve(helmDir, "templates"), { recursive: true });

  // Write Chart.yaml
  const chartYaml = `apiVersion: v2
name: ${ctx.config.name}
description: ${ctx.config.description || ctx.config.name}
type: application
version: 1.0.0
appVersion: "1.0.0"
`;
  await writeFile(resolve(helmDir, "Chart.yaml"), chartYaml);

  // Write values.yaml with defaults
  const registry = mergedConfig.registry;
  const uiImageName = registry ? `${registry}/${projectName}-ui` : `localhost/${projectName}-ui`;
  const msImageName = registry ? `${registry}/${projectName}-ms` : `localhost/${projectName}-ms`;
  const rtImageName = registry ? `${registry}/${projectName}-rt` : `localhost/${projectName}-rt`;
  const storageImageName = registry
    ? `${registry}/converged-storage`
    : `localhost/converged-storage`;
  const pullPolicy = registry ? "Always" : "Never";
  const ingressHosts = mergedConfig.ingress?.hosts ?? [`${targetNamespace}.test`];
  const hostsYaml = ingressHosts.map((h) => `    - ${h}`).join("\n");
  const valuesYaml = `ingress:
  hosts:
${hostsYaml}

images:
  ui:
    name: ${uiImageName}
    tag: latest
    pullPolicy: ${pullPolicy}
  ms:
    name: ${msImageName}
    tag: latest
    pullPolicy: ${pullPolicy}
  rt:
    name: ${rtImageName}
    tag: latest
    pullPolicy: ${pullPolicy}
  storage:
    name: ${storageImageName}
    tag: latest
    pullPolicy: ${pullPolicy}
`;
  await writeFile(resolve(helmDir, "values.yaml"), valuesYaml);

  // cdk8s synth writes templates directly
  generateKubernetesManifests(ctx);
  console.log(`  ${helmDir}`);

  // Package Helm chart as .tgz
  console.log("\nPackaging Helm chart...");
  const chartName = `${ctx.config.name}-${presetName}-1.0.0.tgz`;
  const chartPath = resolve(presetDir, chartName);

  const proc = Bun.spawn(
    ["tar", "-czf", chartPath, "-C", helmDir, "."],
    { stdout: "inherit", stderr: "inherit" },
  );
  await proc.exited;

  if (proc.exitCode === 0) {
    console.log(`  ${chartPath}`);
  } else {
    console.error("  Failed to create archive");
  }

  // Generate K3s HelmChart CRD with embedded chart
  console.log("\nGenerating K3s HelmChart CRD...");
  const chartBytes = await Bun.file(chartPath).arrayBuffer();
  const chartBase64 = Buffer.from(chartBytes).toString("base64");
  generateKubernetesManifests(ctx, chartBase64);
  console.log(`  ${resolve(presetDir, "k3s-chart.yaml")}`);

  // Generate runtime configs (per-container config.json with service host map)
  console.log("\nGenerating runtime configs...");
  const configsDir = resolve(presetDir, "configs");
  await mkdir(configsDir, { recursive: true });
  const runtimeConfigs = generateRuntimeConfigs(ctx);
  for (const [filename, content] of runtimeConfigs) {
    const path = resolve(configsDir, filename);
    await writeFile(path, content);
    console.log(`  ${path}`);
  }

  // Summary
  const summary = {
    project: projectName,
    preset: presetName,
    generatedAt: new Date().toISOString(),
    containers: containers.map((c) => ({
      name: c.name,
      landing: c.landing,
      spa: c.spa,
      microfrontends: c.microfrontends.map((m) => m.name),
      microservices: c.microservices.map((s) => `${s.category}/${s.name}`),
    })),
    storage: mergedConfig.storage,
    ingress: mergedConfig.ingress,
  };

  const summaryPath = resolve(presetDir, "summary.json");
  await writeFile(summaryPath, JSON.stringify(summary, null, 2));
  console.log(`\nSummary: ${summaryPath}`);

  console.log("\nBuild complete!");
}
