// Frontend config is now part of the unified runtime config
// generated by server.ts -> generateRuntimeConfigs()
// This module is kept for backwards compatibility.

import type { GeneratorContext } from "../types";

export function generateFrontendConfigs(
  _ctx: GeneratorContext,
): Map<string, string> {
  return new Map();
}
