import type {
  CallsService,
  Call,
  CallId,
  CallRecordId,
  CallDialogueItem,
  CallRecordingInput,
  CallRecordingResult,
  CallAudioId,
  CallFragmentId,
  CallFragmentSource,
  CallFragmentInput,
  CallFragmentInfo,
  CallDeleteResult,
  CallContextName,
  CallContext,
  CallContextInput,
  CallContextSummary,
  CallContextListParams,
  CallDialogueInput,
  CallsListParams,
  PaginatedResult,
} from "g-calls";

export type {
  CallsService,
  Call,
  CallId,
  CallRecordId,
  CallDialogueItem,
  CallRecordingInput,
  CallRecordingResult,
  CallAudioId,
  CallFragmentId,
  CallFragmentSource,
  CallFragmentInput,
  CallFragmentInfo,
  CallDeleteResult,
  CallContextName,
  CallContext,
  CallContextInput,
  CallContextSummary,
  CallContextListParams,
  CallDialogueInput,
  CallsListParams,
  PaginatedResult,
};
