import type {
  VideoService,
  CameraId,
  VideoStreamId,
  VideoSegmentId,
  ISODateString,
  Camera,
  CameraInput,
  VideoStream,
  VideoStreamInput,
  VideoSegment,
  VideoSegmentInput,
  VideoSegmentListParams,
  PaginationParams,
  PaginatedResult,
  VideoThumbSaveInput,
} from "g-video";

export type {
  VideoService,
  CameraId,
  VideoStreamId,
  VideoSegmentId,
  ISODateString,
  Camera,
  CameraInput,
  VideoStream,
  VideoStreamInput,
  VideoSegment,
  VideoSegmentInput,
  VideoSegmentListParams,
  PaginationParams,
  PaginatedResult,
  VideoThumbSaveInput,
};
