FROM alpine:3.20 AS runtime
WORKDIR /app

COPY ./zig-out/bin /app/storage
RUN chmod +x /app/storage && mkdir -p /app/data /app/socket && chown -R 1000:1000 /app
RUN adduser -D -u 1000 default || true
USER 1000

CMD ["/app/storage", "start", "--data-dir", "/app/data", "--socket", "/app/socket/storage.sock"]
