export type {
  FlushResult,
  ListMetaParams,
  SetDataParams,
  SetMetaParams,
  SetStatusPatternParams,
  SetStatusPatternResult,
  StaticContentType,
  StaticMeta,
  StaticMetaListResult,
  StaticService,
	StaticStatus,
	FilterObject,
	SelectionDescriptor,
	SelectionStats,
} from "g-static";
