export type {
  StaffService,
  StaffMember,
  StaffInput,
  StaffUpdate,
  StaffId,
  Shift,
  ShiftInput,
  ShiftUpdate,
  ShiftId,
  Absence,
  AbsenceInput,
  AbsenceId,
  WorkId,
  StaffListParams,
  ShiftListParams,
  AbsenceListParams,
  PaginatedResult,
  ISODateString,
} from "g-staff";
