export type {
  WebhooksService,
  WebhookEndpoint,
  WebhookEndpointInput,
  WebhookEndpointUpdate,
  WebhookEndpointListParams,
  WebhookLogEntry,
  WebhookLogListParams,
  ProviderDefinition,
  ProviderParam,
  PaginatedResult,
  FilterObject,
  SelectionDescriptor,
  SelectionStats,
} from "g-webhooks";
