import type {
  CommunityService,
  CommunitySection,
  CommunitySectionInput,
  CommunityTopic,
  CommunityTopicInput,
  ListParams,
  PaginatedResult,
  SectionId,
  SectionListParams,
  SectionTreeNode,
  ThreadId,
  TopicId,
  TopicListParams,
  UserId,
  FilterObject,
  SelectionDescriptor,
  SelectionStats,
} from "g-community";

export type {
  CommunityService,
  CommunitySection,
  CommunitySectionInput,
  CommunityTopic,
  CommunityTopicInput,
  ListParams,
  PaginatedResult,
  SectionId,
  SectionListParams,
  SectionTreeNode,
  ThreadId,
  TopicId,
  TopicListParams,
  UserId,
  FilterObject,
  SelectionDescriptor,
  SelectionStats,
};
