import type {
  ChatsService,
  ChatContext,
  ChatContextSummary,
  ChatRoom,
  ChatRoomId,
  ChatRoomRole,
  ChatRoomType,
  ChatRoomUser,
  ChatRoomsListParams,
  ChatRoomsListResult,
  ChatThreadId,
  ChatUserId,
  CreateChatRoomInput,
  PaginatedResult,
  PaginationParams,
  UpdateChatRoomInput,
} from "g-chats";

export type {
  ChatsService,
  ChatContext,
  ChatContextSummary,
  ChatRoom,
  ChatRoomId,
  ChatRoomRole,
  ChatRoomType,
  ChatRoomUser,
  ChatRoomsListParams,
  ChatRoomsListResult,
  ChatThreadId,
  ChatUserId,
  CreateChatRoomInput,
  PaginatedResult,
  PaginationParams,
  UpdateChatRoomInput,
};
