export type {
	Contact,
	ImportContact,
	ImportItem,
	ImportLead,
	Lead,
	LeadEvent,
	LeadListParams,
	LeadTag,
	LeadUpdate,
	Offer,
	Outreach,
	OutreachCandidate,
	OutreachTarget,
	OutreachTargetInput,
	OutreachTargetListParams,
	NormalizeImportLeadsInput,
	NormalizeImportLeadsResult,
	OutreachTargetStatusUpdate,
	PaginatedResult,
	ParseImportLeadsInput,
	ParseImportLeadsResult,
	PaginationParams,
	SalesService,
	Statistic,
	Touch,
} from "g-sales";
