#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { InterfaceParser } from "./generator/parser";

const typesFile = process.argv[2];
const outputFile = process.argv[3];
const transportImport = process.argv[4] ?? "transport";

if (!typesFile || !outputFile) {
	console.error(
		"Usage: zig-generator <types-file> <output-file> [transport-import]",
	);
	process.exit(1);
}

const metadata = new InterfaceParser().parseInterface(resolve(typesFile));
const zigIdentifier = (value: string) => value.replace(/[^A-Za-z0-9_]/g, "_");
const methods = metadata.methods
	.map(
		(method) => `pub fn ${zigIdentifier(method.name)}(
    runtime: *transport.Runtime,
    scope: []const u8,
    body: []const u8,
    completion: transport.RuntimeCompletion,
) !void {
    return runtime.request(.{
        .service = service,
        .method = "${method.name}",
        .scope = scope,
        .body = body,
    }, completion);
}`,
	)
	.join("\n\n");

const policies = metadata.methods
	.map(
		(method) => `    .{ .service = service, .method = "${method.name}", .level = .user, .mode = null },`,
	)
	.join("\n");

const code = `// Generated by nrpc/src/zig-generator.ts. Do not edit manually.
const std = @import("std");
const transport = @import("${transportImport}");

pub const service = "${metadata.serviceName}";

/// Server-side NRPC descriptor. A native application calls verifyAndAuthorize
/// before its handwritten handler; this generated code never knows the handler.
pub const method_policies = [_]transport.auth.authorize.MethodPolicy{
${policies}
};

pub fn policy(method: []const u8) ?transport.auth.authorize.MethodPolicy {
    for (method_policies) |entry| {
        if (std.mem.eql(u8, entry.method, method)) return entry;
    }
    return null;
}

pub fn verifyAndAuthorize(
    allocator: std.mem.Allocator,
    raw_token: []const u8,
    verifier: transport.auth.jwt.Config,
    now_unix: i64,
    method: []const u8,
) !transport.auth.jwt.VerifiedToken {
    const method_policy = policy(method) orelse return error.MethodUnavailable;
    var token = try transport.auth.jwt.verify(allocator, raw_token, verifier, now_unix);
    errdefer token.deinit(allocator);
    try transport.auth.authorize.authorize(token.toClaims(), method_policy);
    return token;
}

${methods}
`;

const outputPath = resolve(outputFile);
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, code);
console.log(`Generated Zig NRPC client: ${outputPath}`);
