// Generated by build/bundles.ts: project audit route module.
export const hasAuditPage = true;
export { bootstrapAudit } from "../../../../../club/front/landing/src/audit/client/landing";
export { bootstrapAuditPrint } from "../../../../../club/front/landing/src/audit/client/print";
