// Generated by build/bundles.ts: project audit route module.
export const hasAuditPage = true;
export { bootstrapAudit } from "../../../../../../club/core/frontend/landing/src/audit/client/landing";
export { bootstrapAuditPrint } from "../../../../../../club/core/frontend/landing/src/audit/client/print";
