#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { InterfaceParser } from "./generator/parser";

const typesFile = process.argv[2];
const outputFile = process.argv[3];
const providerImport = process.argv[4] ?? "../nrpc/gateway.zig";

if (!typesFile || !outputFile) {
	console.error(
		"Usage: zig-generator <types-file> <output-file> [provider-import]",
	);
	process.exit(1);
}

const metadata = new InterfaceParser().parseInterface(resolve(typesFile));
const methods = metadata.methods
	.map(
		(method) => `pub fn ${method.name}(
	provider: *nrpc.Provider,
	scope: []const u8,
	body: []const u8,
) !nrpc.Response {
	return provider.call(.{
		.service = service,
		.method = "${method.name}",
		.scope = scope,
		.body = body,
	});
}`,
	)
	.join("\n\n");

const code = `// Generated by nrpc/src/zig-generator.ts. Do not edit manually.
const nrpc = @import("${providerImport}");

pub const service = "${metadata.serviceName}";

${methods}
`;

const outputPath = resolve(outputFile);
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, code);
console.log(`Generated Zig NRPC client: ${outputPath}`);
