export type { OperationAuthorizationController } from "./authorization";
export {
	authorizeObjectType,
	authorizeOperation,
	canDiscover,
	canExecuteOperation,
	OperationAuthorizationError,
	onOperationAuthorizationChanged,
	setOperationAuthorizationController,
} from "./authorization";
export type { OperatorCatalogEntry } from "./catalog";
export {
	catalogEntries,
	catalogEntry,
	invokeCatalogEntry,
	localized,
	invokeOperator,
	operatorCandidateEntries,
	operatorCatalogEntries,
	operatorCatalogEntry,
	operatorTargets,
	searchOperatorCatalog,
} from "./catalog";
export {
	$focus,
	attachToFocus,
	type FocusItem,
	focusCleared,
	focusDetached,
	focusedObject,
	focusedRef,
	focusedRefs,
	focusItems,
	focusKey,
} from "./focus";
export {
	$objectRegistryRevision,
	ingestObjectIndex,
	loadObjectIndex,
	surfaceDeclared,
	surfaceRegistered,
	ObjectRegistry,
	objectRegistry,
} from "./registry";
export type { OwnedOperation } from "./resolver";
export {
	ObjectResolver,
	objectResolver,
	operationsFor,
	resolve,
} from "./resolver";
export {
	$objectRevisions,
	executeOperation,
	loadObjectType,
	objectChanged,
	objectRefreshRequested,
	objectRevisionKey,
	operationExecutionFailed,
	operationExecutionStarted,
	operationExecutionSucceeded,
	presentReference,
	referencePresented,
	refreshFocusedObjects,
	registerSurface,
	setSurfaceLoader,
} from "./runtime";
export type {
	CategoryId,
	DiscoveryAccess,
	DomainRef,
	ExecuteOperationRequest,
	IdSelection,
	SurfaceDefinition,
	SurfaceManifest,
	ObjectChange,
	ObjectDefinition,
	ObjectIndexFile,
	ObjectIndexModule,
	ObjectRef,
	ObjectTypeDefinition,
	ObjectTypeId,
	OperationContext,
	OperationDefinition,
	OperationId,
	OperationInput,
	OperationParameters,
	Operator,
	PresentationSource,
	PresentedReference,
	PresentReferenceOptions,
	QuerySelection,
	RefKind,
	ResolutionCandidate,
	ResolveContext,
	SetRef,
	SetSelection,
	StatisticDefinition,
	StatisticRole,
	StatisticWidgetSize,
	TypeExpression,
	ViewDefinition,
	ViewId,
	ViewRuntimeProps,
} from "./types";
export type {
	LlmCatalogParameters,
	SurfaceLlmAction,
	SurfaceLlmCatalog,
} from "../llm-catalog";
export {
	Category,
	defineSurface,
	NEW_OBJECT_ID,
	OPERATORS,
	objectOf,
	objectRef,
	setOf,
	setRef,
} from "./types";
