export type { OperationAuthorizationController } from "./authorization";
export {
	authorizeObjectType,
	authorizeOperation,
	canDiscover,
	canExecuteOperation,
	OperationAuthorizationError,
	onOperationAuthorizationChanged,
	setOperationAuthorizationController,
} from "./authorization";
export type { OperatorCatalogEntry } from "./catalog";
export {
	catalogEntries,
	catalogEntry,
	invokeCatalogEntry,
	invokeOperator,
	operatorCandidateEntries,
	operatorCatalogEntries,
	operatorCatalogEntry,
	operatorTargets,
	searchOperatorCatalog,
} from "./catalog";
export {
	$objectRegistryRevision,
	ingestObjectIndex,
	loadObjectIndex,
	microfrontendDeclared,
	microfrontendRegistered,
	ObjectRegistry,
	objectRegistry,
} from "./registry";
export { ObjectResolver, objectResolver, resolve } from "./resolver";
export {
	executeOperation,
	loadObjectType,
	operationExecutionFailed,
	operationExecutionStarted,
	operationExecutionSucceeded,
	presentReference,
	referencePresented,
	registerMicrofrontend,
	setMicrofrontendLoader,
} from "./runtime";
export type {
	CategoryId,
	DiscoveryAccess,
	DomainRef,
	ExecuteOperationRequest,
	IdSelection,
	MicrofrontendDefinition,
	MicrofrontendManifest,
	ObjectDefinition,
	ObjectIndexFile,
	ObjectIndexModule,
	ObjectRef,
	ObjectTypeDefinition,
	ObjectTypeId,
	OperationContext,
	OperationDefinition,
	OperationId,
	OperationInput,
	OperationParameters,
	Operator,
	PresentationSource,
	PresentedReference,
	PresentReferenceOptions,
	QuerySelection,
	RefKind,
	ResolutionCandidate,
	ResolveContext,
	SetRef,
	SetSelection,
	TypeExpression,
	ViewDefinition,
	ViewId,
	ViewRuntimeProps,
} from "./types";
export {
	Category,
	defineMicrofrontend,
	OPERATORS,
	objectOf,
	objectRef,
	setOf,
	setRef,
} from "./types";
